version: '2'
services:
  redis:
    restart: always
    image: redis
    # ports:
    #  - "6379:6379"

  django:
    restart: always
    build: backend
    command: gunicorn website.wsgi:application -b :8081 --reload
    ports:
      - "8081:8081"
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./backend:/code
      - ~/.ssh:/root/.ssh

  rqworker:
    restart: always
    build: backend
    command: python manage.py rqworker
    links:
      - redis
      - django
    depends_on:
      - redis
      - django
  vue:
    restart: always
    build: frontend
    command: npm run test
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/code
