version: '3'

services:
  django:
    environment:
      - DEBUG=False

  rqworker:
    environment:
      - DEBUG=False

  vue:
    restart: 'no'
    command: bash -c "npm run build && echo 'Vue will now stop.'"
    volumes:
      - website-dist:/code/dist

  nginx:
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /cert:/cert
      - website-dist:/website
    ports:
      - "443:443"

volumes:
     website-dist:
