version: '2'

services:

  redis:
    restart: always
    image: redis

  django:
    build:
      context: backend
    command: python manage.py test
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./backend:/code

  rqworker:
    restart: always
    build: backend
    command: ./rqworker_reload.sh
    links:
      - redis
      - django
    depends_on:
      - redis
      - django
    volumes:
      - ./backend:/code
