version: '2'

services:

  redis:
    restart: always
    image: redis

  django:
    restart: always
    build:
      context: backend
    command: gunicorn website.wsgi:application -b :8082 --reload
    ports:
      - "8082:8082"
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./backend:/code

  rqworker:
    restart: always
    build: backend
    command: ./rqworker_reload.sh
    links:
      - redis
      - django
    depends_on:
      - redis
      - django
    volumes:
      - ./backend:/code

  vue:
    restart: always
    build: frontend
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/code
      - /code/node_modules
